// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
})

import TestHomeIcon from './TestHomeIcon.vue'

// Export components individually
export { TestHomeIcon }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('TestHomeIcon', TestHomeIcon)
}

// Export the library as a plugin
export default { install: install }
