// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
})

import ExampleCard from './ExampleCard.vue'
import HomeIcon from './HomeIcon.vue'

// Export components individually
export { ExampleCard, HomeIcon }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('ExampleCard', ExampleCard)
  Vue.component('HomeIcon', HomeIcon)
}

// Export the library as a plugin
export default { install: install }
